server:
  port: 8100

spring:
  application:
    name: content-account-verifier

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:9000/eureka}
  instance:
    instance-id: content-account-verifier-${random.uuid}

management:
  endpoint:
    health:
      show-components: always
      show-details: always
      status:
        http-mapping:
          up: 207
  endpoints:
    web:
      exposure:
        include: health, info, env, beans, metrics, prometheus
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
info:
  app:
    name: Content account verifier
    description: App is used to verify existence of content accounts
    version: 1.0.0